name: CI

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
...

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip & install minimal tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install ruff flake8 pytest

      - name: Lint (ruff)
        # lint all python packages / folders; ruff exits non-zero on issues, so keep '|| true' if you want non-blocking
        run: |
          ruff nlp_core bim_core || true

      - name: Run tests (pytest) — run only if tests exist
        run: |
          if git ls-files | grep -E '^tests/|test_.*\.py' >/dev/null 2>&1; then
            echo "Tests found — running pytest"
            pytest -q
          else
            echo "No tests found — skipping pytest"
          fi

      # ---------------------------
      # Optional: install project deps (heavy). Uncomment if you need to run integration tests that require them.
      # - name: Install project requirements (optional, may be slow)
      #   run: |
      #     python -m pip install -r nlp_core/requirements.txt
      # ---------------------------

      - name: Build NLP Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.nlp
          tags: draftai/nlp:latest
          push: false
          load: true

      - name: Build BIM Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bim
          tags: draftai/bim:latest
          push: false
          load: true

      - name: Build MCP-client Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.mcp-client
          tags: draftai/mcp-client:latest
          push: false
          load: true

      - name: Install mkdocs & build docs (for gh-pages)
        if: github.ref == 'refs/heads/main'
        run: |
          python -m pip install mkdocs mkdocs-material
          mkdocs build -d site

      - name: Publish docs to gh-pages (optional)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
