name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install shared deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install ruff flake8 pytest

      - name: Lint (ruff)
        run: |
          source .venv/bin/activate
          ruff nlp_core bim_core || true

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q || true

      - name: Build NLP Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.nlp
          tags: draftai/nlp:latest
          push: false

      - name: Build BIM Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bim
          tags: draftai/bim:latest
          push: false

      - name: Build MCP Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.mcp-client
          tags: draftai/mcp:latest
          push: false
      - name: Prepare docs directory
        run: |
          mkdir -p site
          echo "<h1>DraftAI docs placeholder</h1>" > site/index.html
      - name: Publish docs to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT_CLASSIC }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: true
          force_orphan: true

      - name: Run MCP tests
        if: false
        run: echo "MCP tests disabled"
